name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: "Ruby ${{ matrix.ruby-version }} ActiveSupport: ${{matrix.activesupport-version}}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
        activesupport-version: ['5', '6']
    env:
      ACTIVESUPPORT_MAJOR: ${{ matrix.activesupport-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
