name: CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.2", "3.3", "3.4", "4.0"]
        bundler: [default]
        gemfile:
          - active_support_7
          - active_support_8
        include:
          - { ruby: "2.3", gemfile: "active_support_3", bundler: "1" }
          - { ruby: "2.4", gemfile: "active_support_4", bundler: "1" }
          - { ruby: "2.5", gemfile: "active_support_4", bundler: "1" }
          - { ruby: "2.5", gemfile: "active_support_5", bundler: "1" }
          - { ruby: "2.6", gemfile: "active_support_5", bundler: "1" }
          - { ruby: "2.6", gemfile: "active_support_6", bundler: "1" }
          - { ruby: "2.7", gemfile: "active_support_6" }
          - { ruby: "2.7", gemfile: "active_support_7" }
          - { ruby: "3.0", gemfile: "active_support_7" }
          - { ruby: "3.1", gemfile: "active_support_7" }

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: true # runs `bundle install` and caches gems automatically
      - name: Run tests
        run: bundle exec rake
